params:
  class_weight:
      0: 1
      1: 2
  kernel: rbf
  gamma: scale
  decision_function_shape: ovr
  C: 160
  probability: True

add_params:
  windows:
      - 500
      - 1000
      - 2000
      - 5000
  step: 5
  plot: False

files:
  sequence: chromosome1.fasta
  cds: cds.csv
  cds_location: last_cds_location.csv
  exons: exons.csv
  features: end_features.csv
  
paths:
  data: data
  log: log
