add_params:
  plot: false
  step: 5
  windows:
    - 50
    - 100
    - 200
    - 300
files:
  cds: cds.csv
  cds_location: first_cds_location.csv
  end_features: end_features.csv
  exons: exons.csv
  features: start_features.csv
  first_cds_location: first_cds_location.csv
  last_cds_location: last_cds_location.csv
  sequence: chromosome1.fasta
  start_features: start_features.csv
params:
  C: 98.24230233796422
  class_weight:
    0: 1
    1: 2
  decision_function_shape: ovo
  gamma: scale
  kernel: linear
  probability: true
  tol: 0.0386488981125862
paths:
  data: data
  log: log
preprocess_params:
  end_max_length: 15000
  end_min_length: 100
  num_of_samples: 2000
  start_max_length: 1500
  start_min_length: 50
