params:
  class_weight:
      0: 1
      1: 3
  kernel: rbf
  gamma: scale
  decision_function_shape: ovo
  C: 145
  tol: 0.0623563
  probability: True

add_params:
  windows:
      - 250
      - 500
      - 1000
      - 2000
  step: 5
  plot: True

files:
  sequence: chromosome1.fasta
  cds: cds.csv
  cds_location: last_cds_location.csv
  exons: exons.csv
  features: end_features.csv
  
paths:
  data: data
  log: log
