add_params:
  plot: true
  step: 5
  windows:
  - 250
  - 500
  - 1000
  - 2000
files:
  cds: cds.csv
  cds_location: last_cds_location.csv
  exons: exons.csv
  features: end_features.csv
  sequence: chromosome1.fasta
params:
  C: 165.64405117819743
  class_weight:
    0: 1
    1: 2
  decision_function_shape: ovo
  gamma: auto
  kernel: rbf
  probability: true
  tol: 0.062356369678597236
paths:
  data: data
  log: log
