add_params:
  data: test
  num_of_plots: 3
  plot: true
  step: 5
  windows:
  - 10
  - 25
files:
  cds: cds.csv
  cds_location: first_cds_location.csv
  codon_loc: start_codon_location.csv
  end_features: end_features.csv
  exons: exons.csv
  features: start_features.csv
  first_cds_location: first_cds_location.csv
  last_cds_location: last_cds_location.csv
  sequence: chromosome1.fasta
  start_features: start_features.csv
params:
  C: 85.73095986778094
  class_weight:
    0: 1
    1: 2
  decision_function_shape: ovo
  gamma: scale
  kernel: rbf
  tol: 0.08917730007820798
paths:
  data: data
  log: log
preprocess_params:
  end_max_length: 15000
  end_min_length: 100
  num_of_samples: 2000
  start_max_length: 1500
  start_min_length: 50
