add_params:
  plot: true
  step: 5
  data: train
  num_of_plots: 3
  windows:
  - 100
files:
  cds: cds.csv
  cds_location: first_cds_location.csv
  exons: exons.csv
  features: start_features.csv
  sequence: chromosome1.fasta
  codon_loc: start_codon_location.csv
params:
  C: 196.7236684465528
  class_weight:
    0: 1
    1: 1
  decision_function_shape: ovr
  gamma: auto
  kernel: rbf
  tol: 0.07805291762864555
paths:
  data: data
  log: log
