
model_params:
  class_weight: 3
  windows: 
      - 50
      - 100
      - 200
      - 1000
  left_boundary: 1000
  right_boundary: 1000
  step: 5

preprocess_params:
  num_of_samples: 6000

files:
  sequence: chromosome1.fasta
  cds: cds.csv
  first_cds_location: first_cds_location.csv
  last_cds_location: last_cds_location.csv
  exons: exons.csv
  start_features: start_features.csv
  end_features: end_features.csv
  
paths:
  data: data
  log: log
