add_params:
  plot: true
  step: 5
  windows:
  - 50
  - 100
  - 200
  - 400
files:
  cds: cds.csv
  cds_location: first_cds_location.csv
  exons: exons.csv
  features: start_features.csv
  sequence: chromosome1.fasta
params:
  C: 48.69087509365592
  class_weight:
    0: 1
    1: 2
  decision_function_shape: ovr
  gamma: auto
  kernel: linear
  probability: true
  tol: 0.01381829513486138
paths:
  data: data
  log: log
