
model_params:
  class_weight: 3
  windows: 
      - 50
      - 100
      - 200
  left_boundary: 1000
  right_boundary: 1000
  step: 5

preprocess_params:
  num_of_samples: 5

files:
  sequence: chromosome1.fasta
  cds: cds.csv
  cds_location: cds_location_data.csv
  exons: exons.csv
  features: features.csv
  
paths:
  data: data
  log: log
