add_params:
  plot: true
  step: 5
  windows:
    - 50
    - 100
    - 200
    - 300
files:
  cds: cds.csv
  cds_location: first_cds_location.csv
  exons: exons.csv
  features: start_features.csv
  sequence: chromosome1.fasta
params:
  C: 98.24230233796422
  class_weight:
    0: 1
    1: 2
  decision_function_shape: ovo
  gamma: scale
  kernel: linear
  probability: true
  tol: 0.0386488981125862
paths:
  data: data
  log: log
