params:
  class_weight:
      0: 1
      1: 2
  kernel: linear
  gamma: scale
  decision_function_shape: ovo
  C: 110
  probability: True

add_params:
  windows: 
      - 50
      - 100
      - 200
      - 300
  step: 5
  plot: False

files:
  sequence: chromosome1.fasta
  cds: cds.csv
  cds_location: first_cds_location.csv
  exons: exons.csv
  features: start_features.csv
  
paths:
  data: data
  log: log
